#!/bin/sh /etc/rc.common
START=96
STOP=10
USE_PROCD=1
start_service() {
    umask 077
    procd_open_instance
    procd_set_param command /usr/sbin/radarsender serve
    procd_set_param user root
    procd_set_param respawn 3600 5 5
    procd_set_param term_timeout 20
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
