'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../openwrt/root/www/luci-static/resources/view/radarsender/main_v0_1_2.js'), 'utf8');
const FIXTURE = 'https://192.0.2.10:18880#local-fixture';
const NEXT = 'https://192.0.2.10:18880#replacement-fixture';
function element(tag, attrs = {}, children = []) {
    const node = { tag, value: '', disabled: false, readOnly: false, textContent: '', children, style: {} };
    Object.assign(node, attrs);
    if (typeof attrs.style === 'string') node.style = Object.fromEntries(attrs.style.split(';').filter(Boolean).map(p => p.split(':')));
    if ('value' in attrs) node.value = String(attrs.value);
    Object.defineProperty(node, 'innerHTML', { set() { throw Error('UI must never insert sensitive HTML'); } });
    return node;
}
function count(node, tag) {
    if (!node || typeof node !== 'object') return 0;
    const children = Array.isArray(node.children) ? node.children : [node.children];
    return Number(node.tag === tag) + children.reduce((n, child) => n + count(child, tag), 0);
}
async function setup(options = {}) {
    const calls = [];
    let saved = options.saved === undefined ? FIXTURE : options.saved;
    let current = { ok: true, state: 'idle', config: {}, has_channel: !!saved, ...options.status };
    const rpc = { declare(spec) { return async (...args) => {
        calls.push({ method: spec.method, args });
        if (spec.method === 'status') return current;
        if (spec.method === 'channel') {
            assert.equal(options.readonly, undefined, 'readonly must never fetch channel');
            if (options.failRead) throw Error('fixture read denied');
            return { ok: true, channel: saved };
        }
        if (spec.method === 'configure') {
            if (options.failSave) return { ok: false, error: '保存失败' };
            if (args[0]) saved = args[0];
            current = { ...current, has_channel: !!saved };
            if (current.state === 'waiting_channel') current = { ...current, state: 'connecting', error: '' };
        }
        if (spec.method === 'start') current = { ...current, state: 'connecting' };
        if (spec.method === 'stop') current = { ...current, state: 'stopping' };
        return { ok: true };
    }; } };
    const app = new Function('view', 'rpc', 'poll', 'E', 'L', source)({ extend: x => x }, rpc, { add() {} }, element, { hasViewPermission: () => !options.readonly });
    app.root = app.render(await app.load());
    return { app, calls, setStatus(value) { current = { ...current, ...value }; }, setSaved(value) { saved = value; } };
}
const mutations = calls => calls.filter(c => ['configure', 'start', 'stop'].includes(c.method));
(async () => {
    assert.equal(source.includes('innerHTML'), false);
    const { app, calls } = await setup();
    assert.equal(count(app.root, 'input'), 1);
    assert.equal(count(app.root, 'button'), 2);
    assert.equal(app.channel.type, 'text');
    assert.equal(app.channel.value, FIXTURE);
    assert.equal(app.resume.style.display, 'none');
    assert.match(app.warning.children, /明文/);
    app.channel.value = NEXT;
    app.channel.input();
    await Promise.all([app.action(), app.action()]);
    assert.deepEqual(mutations(calls).map(c => c.method), ['configure', 'start']);
    assert.deepEqual(calls.find(c => c.method === 'configure').args, [NEXT]);
    assert.equal(app.channel.value, NEXT);
    assert.equal(app.toggle.textContent, '断开连接');
    assert.equal(app.channel.disabled, false);
    assert.equal(app.channel.readOnly, true);
    await app.action();
    assert.deepEqual(mutations(calls).map(c => c.method), ['configure', 'start', 'stop']);
    assert.equal(app.toggle.disabled, true);
    app.update({ ok: true, state: 'reconnecting', retry_seconds: 2, error: '网络中断', capturing: true, captured: 12, offline_dropped: 12, dropped: 12 });
    assert.equal(app.state.textContent, '持续采集中，等待服务器');
    assert.match(app.error.textContent, /2 秒/);
    assert.match(app.counters.textContent, /离线 12/);
    assert.equal(app.channel.disabled, false);
    assert.equal(app.channel.readOnly, true);
    assert.equal(app.toggle.disabled, false);
    const waiting = await setup({ status: { state: 'waiting_channel', capturing: true, error: '认证失败' } });
    assert.equal(waiting.app.active, true);
    assert.equal(waiting.app.state.textContent, '持续采集中，等待有效通道');
    assert.equal(waiting.app.toggle.textContent, '断开连接');
    assert.equal(waiting.app.toggle.disabled, false);
    assert.equal(waiting.app.channel.disabled, false);
    assert.equal(waiting.app.channel.readOnly, false);
    assert.equal(waiting.app.resume.style.display, '');
    waiting.app.update({ ...waiting.app.data, capturing: false });
    assert.equal(waiting.app.state.textContent, '等待有效通道');
    waiting.app.update({ ...waiting.app.data, capturing: true });
    for (const bad of ['', FIXTURE, 'nonsense', 'ftp://192.0.2.10#x', 'https://192.0.2.10#', 'https://192.0.2.10#%00', 'https://192.0.2.10/path#x', 'https://192.0.2.10?x=1#x', 'https://u:p@192.0.2.10#x', 'https://192.0.2.10:0#x', 'https://192.0.2.10:#x', 'https://192.0.2.10:/#x', 'https://[::1]:/multi/channel/ingest#x', 'https://192.0.2.10#%ZZ', 'x'.repeat(4097)]) {
        waiting.app.channel.value = bad;
        waiting.app.channel.input();
        await waiting.app.replaceChannel();
        assert.equal(mutations(waiting.calls).length, 0, bad);
        assert.ok(waiting.app.error.textContent);
    }
    waiting.app.channel.value = NEXT;
    waiting.app.channel.input();
    await Promise.all([waiting.app.replaceChannel(), waiting.app.replaceChannel(), waiting.app.action()]);
    assert.deepEqual(mutations(waiting.calls).map(c => c.method), ['configure']);
    assert.equal(waiting.app.channel.value, NEXT);
    assert.equal(waiting.app.channel.disabled, false);
    assert.equal(waiting.app.channel.readOnly, true);
    assert.equal(waiting.app.resume.style.display, 'none');
    const disconnect = await setup({ status: { state: 'waiting_channel', capturing: true } });
    await disconnect.app.action();
    assert.deepEqual(mutations(disconnect.calls).map(c => c.method), ['stop']);
    const editing = await setup({ status: { state: 'waiting_channel' } });
    editing.app.channel.focus();
    editing.setSaved(NEXT);
    await editing.app.refresh();
    assert.equal(editing.app.channel.value, FIXTURE, 'focused editor cannot be overwritten');
    editing.app.channel.value = 'https://192.0.2.10#unfinished-edit';
    editing.app.channel.input();
    editing.app.channel.blur();
    await editing.app.refresh();
    assert.equal(editing.app.channel.value, 'https://192.0.2.10#unfinished-edit', 'dirty editor cannot be overwritten');
    assert.equal(editing.app.savedChannel, NEXT);
    const clean = await setup();
    clean.setSaved(NEXT);
    await clean.app.refresh();
    assert.equal(clean.app.channel.value, NEXT, 'untouched editor may reflect current persisted channel');
    const failed = await setup({ failSave: true, status: { state: 'waiting_channel' } });
    failed.app.channel.value = NEXT;
    failed.app.channel.input();
    await failed.app.replaceChannel();
    assert.deepEqual(mutations(failed.calls).map(c => c.method), ['configure']);
    assert.equal(failed.app.channel.value, NEXT);
    assert.equal(failed.app.error.textContent, '保存失败');
    await failed.app.refresh();
    assert.equal(failed.app.channel.value, NEXT);
    assert.equal(failed.app.error.textContent, '保存失败', 'poll must not erase failed-save evidence');
    assert.equal(failed.app.busy, false);
    assert.equal(failed.app.channel.disabled, false);
    assert.equal(failed.app.channel.readOnly, false);
    const unsafe = 'https://192.0.2.10#<img src=x onerror=alert(1)>&"\'';
    const sensitive = await setup({ saved: unsafe, status: { state: 'waiting_channel', error: '<script>fixture</script>' } });
    assert.equal(sensitive.app.channel.value, unsafe);
    assert.equal(sensitive.app.error.textContent, '<script>fixture</script>');
    assert.equal(count(sensitive.app.root, 'img'), 0);
    assert.equal(count(sensitive.app.root, 'script'), 0);
    sensitive.app.channel.value = unsafe + 'new';
    sensitive.app.channel.input();
    await sensitive.app.replaceChannel();
    assert.equal(mutations(sensitive.calls).length, 1, 'HTML-sensitive credential bytes are text, not markup');
    for (const state of ['idle', 'waiting_channel', 'sending']) {
        const readonly = await setup({ readonly: true, saved: unsafe, status: { state, config: { channel: unsafe } } });
        assert.equal(readonly.app.channel.value, '', 'readonly must ignore even misbehaving status secret');
        assert.equal(readonly.app.channel.disabled, true);
        assert.equal(readonly.app.toggle.disabled, true);
        assert.equal(readonly.app.resume.style.display, 'none');
        readonly.app.channel.value = NEXT;
        await readonly.app.action();
        await readonly.app.replaceChannel();
        await readonly.app.refresh();
        assert.equal(readonly.calls.every(c => c.method === 'status'), true);
    }
    const recovery = await setup({ saved: '', status: { config_error: '配置损坏', has_channel: false } });
    assert.equal(recovery.app.error.textContent, '配置损坏');
    recovery.app.channel.value = NEXT;
    await recovery.app.action();
    assert.deepEqual(mutations(recovery.calls).map(c => c.method), ['configure', 'start']);
    const broken = await setup({ status: { ok: false, error: '后台未启动' } });
    assert.equal(broken.app.toggle.disabled, true);
    assert.equal(broken.app.error.textContent, '后台未启动');
    assert.equal(broken.app.channel.disabled, true);
    const hidden = await setup({ failRead: true });
    hidden.app.channel.value = '';
    await hidden.app.action();
    assert.deepEqual(mutations(hidden.calls).map(c => c.method), ['configure', 'start']);
    assert.deepEqual(mutations(hidden.calls)[0].args, ['']);
    console.log('PASS UI: plaintext write-ACL channel, safe text, waiting update-only recovery/stop, invalid/same/empty guards, duplicate clicks, editor-preserving polls, failed-save evidence, normal send lock, readonly no secret/RPC, saved reuse and unavailable backend');
})().catch(e => { console.error(e); process.exitCode = 1; });
